### PR TITLE
Update Piggieback, Weasel e ClojureScript

### PR DESCRIPTION
**Pull request by samflores**

### CODE REVIEW

**Comment by driftcrow** [comment]
+1

**Comment by Deraen** [comment]
Does this work?

Ping @piranha, you looked into this if I remember correctly?

There was some problem with Weasel but is that fixed now (https://github.com/tomjakubowski/weasel/commit/fcf63dbe6c64ffa40deb65e3850c8c5068bb75ce)?

**Comment by piranha** [comment]
Yeah, it is fixed so that boot-cljs-repl [can work](https://github.com/modnakasta/boot-cljs-repl/commit/e57654667aede552ee3168cb66b9b8180a3df23c#diff-d5218f3b7e8186c46b12a1bbc41fd0e6R92), but Weasel needs a release.

**Comment by piranha** [comment]
That pull request actually wouldn't help much, BTW (didn't notice that's a pull request and not an issue).

**Comment by samflores** [comment]
I'm using my forked version locally right now.

**Comment by samflores** [comment]
Oops. I didn't notice the link you posted before writing my comment where you already merged the  updates (a bit older versions, tho). I'll try the "official" version. Thanks

**Comment by pkobrien** [comment]
I'm closing this PR since #18 has a more complete fix.

**Pull request closed without merging**
